#!/usr/bin/python2
# coding=utf-8

import os
import sys
import time

time.sleep(1)
os.system('clear')
print
print " Tunggu Sebentar Bangsad :V
time.sleep(3)
print
print
os.system('apt upgrade && apt upgrade -y')
os.system('pkg install python -y')
os.system('pkg install nano')
os.system('pkg install bash')
os.system('pkg install wget')
os.system('pkg install curl')
os.system('pkg install ruby')
os.system('pkg install figlet')
os.system('pkg install clang')
os.system('pkg install futures')
os.system('pip2 install mechanize requests ')
os.system('pip2 install bs4')
os.system('pip install mechanize requests ')
os.system('pip install bs4')
os.system('pip2 install -r requirements.txt')
os.system('pip install -r requirements.txt')
os.system('gem install lolcat')
time.sleep(2)
os.system('clear')